# print('ABC')
# print(444444)
# print([1,2,"AQW"])
# print(1, 2, 3)
# print(1, 'A', [1,2,"AQW"])
# print("Number" + str(3))
# print(1, 2, [], 3, sep='*')
# print("Line1", end=' ')
# print("Line2")

a = input("Enter number: ")
print(a)
print(type(a))
